services:
  admin:
    build:
      dockerfile: Dockerfile
      args:
        DB_PROVIDER: "sqlite"
    environment:
      DATABASE_URL: "file://keystone.db"
    volumes:
      - ./logs:/root/.npm/_logs
    ports:
      - 3000:3000
